title: Tyrux
email: help@monox.ml
description: >-
  Tyrux is a experimental site created by genx to test its applicability and
  resource-fulness.
baseurl: ''
url: tyrux.ml
twitter_username: Genxster4
github_username: genxster1998
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
